# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : 码农时代
tagline: Site Tagline
author :
  name : Joseph
  email : liseor@gmail.com
  github : dholer
  twitter : username
  feedburner : feednam

production_url : http://blog.dhole.inf

JB :
  version : 0.2.13
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

  comments :
    provider : disqus
    disqus :
      short_name : dholeinfo
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
  
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-32230080-1'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'

  sharing :
    provider : false
